version: '3.5'

services:
  frontend: 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_ENV=development

