version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - VITE_APP_BACKEND_ADDRESS=https://localhost/api/prod
    restart: always
    ports:
      - 3000:3000
